services:
  ui-visuaudio:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ui-visuaudio
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    networks:
      - visuaudio-network
networks:
  visuaudio-network:
    driver: bridge
